package tz.elmkusoma.event.domain;

public enum EventType {
    LECTURE, SEMINAR, WEBINAR, WORKSHOP, TUTORIAL,
    PRACTICAL_DEMONSTRATION, GUEST_SESSION, ACADEMIC_TALK,
    PROFESSIONAL_TRAINING, EDUCATIONAL_BROADCAST,
    CONFERENCE_SESSION, OTHER
}
