package tz.elmkusoma.event.domain;

public enum EventStatus {
    DRAFT, REVIEW, PUBLISHED, REGISTRATION_OPEN, REGISTRATION_CLOSED,
    PREPARING, STARTING, LIVE, ENDING, ENDED,
    RECORDING, PROCESSING, REPLAY_AVAILABLE,
    CANCELLED, RESCHEDULED, FULL, FAILED
}
