-- V03: Identity tables already created in V02 (password_reset_tokens, email_verification_tokens, institution_memberships)
-- This migration is intentionally left as a no-op to preserve migration history
