ALTER TABLE assignments ADD COLUMN IF NOT EXISTS assignment_type VARCHAR(50);
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PUBLISHED';
