ALTER TABLE lessons ADD COLUMN IF NOT EXISTS content_type VARCHAR(50);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS video_url VARCHAR(500);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS file_url VARCHAR(500);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
